// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB93RB0SvhWqOHZS4xfWWPwjDCjzHzufp8',
    appId: '1:864961822276:web:4ec1385f1b5b27417b8611',
    messagingSenderId: '864961822276',
    projectId: 'stayzen-93268',
    authDomain: 'stayzen-93268.firebaseapp.com',
    storageBucket: 'stayzen-93268.appspot.com',
    measurementId: 'G-M8Y8R6Y42S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHoX0Qg63rRY6cIo6dgvfBSMrs4xWwDmo',
    appId: '1:864961822276:android:68478cfa5e17eae57b8611',
    messagingSenderId: '864961822276',
    projectId: 'stayzen-93268',
    storageBucket: 'stayzen-93268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2VnHxVj3zzKtrpbKr4BXUMMEqtsw86p8',
    appId: '1:864961822276:ios:e4578f55130e2fa27b8611',
    messagingSenderId: '864961822276',
    projectId: 'stayzen-93268',
    storageBucket: 'stayzen-93268.appspot.com',
    iosBundleId: 'com.example.stayZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2VnHxVj3zzKtrpbKr4BXUMMEqtsw86p8',
    appId: '1:864961822276:ios:a2a3ba8e9180a5397b8611',
    messagingSenderId: '864961822276',
    projectId: 'stayzen-93268',
    storageBucket: 'stayzen-93268.appspot.com',
    iosBundleId: 'com.example.stayZen.RunnerTests',
  );
}
